### ISSUE TITLE
我应用您的之后报了如下的错误哎Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.

### ISSUE THREAD

**Issue by MmingY** [wzyonggege/RNN_poetry_generator#2]
我的环境是:
 Python 3.6.12，Tensrolfow 1.2.0

# python poetry_gen.py --mode sample --head 明月别枝惊鹊
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f2a59875ef0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.

我是通过Docker运行的您的代码，我在网上没有找到解决方法，希望能得到您的帮助，详细的环境是：
# pip list
Package           Version
----------------- ---------
backports.weakref 1.0rc1
bleach            1.5.0
html5lib          0.9999999
Markdown          2.2.0
numpy             1.16.4
pip               21.0.1
protobuf          3.15.6
setuptools        51.1.2
six               1.15.0
tensorflow        1.2.0
Werkzeug          1.0.1
wheel             0.36.2

**Comment by MmingY** [comment]
> 我的环境是:
> Python 3.6.12，Tensrolfow 1.2.0
> 
> # python poetry_gen.py --mode sample --head 明月别枝惊鹊
> WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f2a59875ef0>: Using a concatenated state is slower and will soon be deprecated. Use state_is_tuple=True.
> 
> 我是通过Docker运行的您的代码，我在网上没有找到解决方法，希望能得到您的帮助，详细的环境是：
> 
> # pip list
> Package Version
> 
> backports.weakref 1.0rc1
> bleach 1.5.0
> html5lib 0.9999999
> Markdown 2.2.0
> numpy 1.16.4
> pip 21.0.1
> protobuf 3.15.6
> setuptools 51.1.2
> six 1.15.0
> tensorflow 1.2.0
> Werkzeug 1.0.1
> wheel 0.36.2

**Comment by MmingY** [comment]
我补充一下我的详细错误信息哈：
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f2a59875ef0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
2021-03-25 08:57:42.947436: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2021-03-25 08:57:42.947520: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2021-03-25 08:57:42.947532: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2021-03-25 08:57:42.947539: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2021-03-25 08:57:42.947579: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
TypeError: expected bytes, NoneType found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "poetry_gen.py", line 257, in <module>
    main()
  File "poetry_gen.py", line 246, in main
    print(sample(data, model, head=args.head))
  File "poetry_gen.py", line 187, in sample
    saver.restore(sess, model_file)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
SystemError: <built-in function TF_Run> returned a result with an error set
